# Generated by Django 5.1.1 on 2024-12-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_youtubechannel_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubechannel',
            name='channel_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='channel_url',
            field=models.URLField(),
        ),
    ]
