# Generated by Django 5.1.1 on 2024-12-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='image.png', null=True, upload_to=''),
        ),
    ]
