# Generated by Django 5.1.1 on 2024-12-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoney',
            name='earning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addmoney',
            name='payment',
            field=models.IntegerField(default=0),
        ),
    ]
