# Generated by Django 5.1.1 on 2024-12-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_customer_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_model',
            name='area_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
