# Generated by Django 5.1.1 on 2024-12-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_customer_model_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_model',
            name='terms_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
