# Generated by Django 5.1.1 on 2024-12-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_customer_model_terms_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_model',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10, null=True),
        ),
    ]
