# Generated by Django 5.1.1 on 2024-12-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='Account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
