# Generated by Django 5.1.1 on 2024-12-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_withdraw_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
